{% if CAPI_VERSION == 'v1alpha2' %}
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  name: {{ CLUSTER_NAME }}-controlplane-0
  labels:
    cluster.x-k8s.io/control-plane: "true"
    cluster.x-k8s.io/cluster-name: "{{ CLUSTER_NAME }}"
spec:
  version: {{ KUBERNETES_VERSION }}
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: {{ CLUSTER_NAME }}-controlplane-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: BareMetalMachine
    name: {{ CLUSTER_NAME }}-controlplane-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: BareMetalMachine
metadata:
  name: {{ CLUSTER_NAME }}-controlplane-0
spec:
  image:
    url: {{ IMAGE_URL }}
    checksum: {{ IMAGE_CHECKSUM }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  name: {{ CLUSTER_NAME }}-controlplane-0
spec:
  initConfiguration:
    nodeRegistration:
      name: {{ " '{{ ds.meta_data.name }}' " }}
      kubeletExtraArgs:
        node-labels: 'metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}'
        provider-id: 'metal3://{{ '{{ ds.meta_data.uuid }}' }}'
  preKubeadmCommands:
    - ip link set dev enp2s0 up
    - dhclient enp2s0
    - mv /tmp/akeys /home/ubuntu/.ssh/authorized_keys
    - chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
    - apt update -y
    - netplan apply
    - >-
      apt install net-tools gcc linux-headers-$(uname -r) bridge-utils
      apt-transport-https ca-certificates curl gnupg-agent
      software-properties-common -y
    - apt install -y keepalived && systemctl stop keepalived
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    - echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
    - apt update -y
    - apt install docker-ce docker-ce-cli containerd.io kubelet kubeadm kubectl -y
    - systemctl enable --now docker kubelet
    - if (curl -sk --max-time 10 https://{{ CLUSTER_APIENDPOINT_HOST }}:6443/healthz); then echo "keepalived already running";else systemctl start keepalived; fi
    - usermod -aG docker ubuntu
  postKubeadmCommands:
    - mkdir -p /home/ubuntu/.kube
    - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
    - systemctl enable --now keepalived
    - chown ubuntu:ubuntu /home/ubuntu/.kube/config
  files:
      - path: /etc/keepalived/keepalived.conf
        content: |
          ! Configuration File for keepalived
          global_defs {
              notification_email {
              sysadmin@example.com
              support@example.com
              }
              notification_email_from lb@example.com
              smtp_server localhost
              smtp_connect_timeout 30
          }
          vrrp_instance VI_2 {
              state MASTER
              interface enp2s0
              virtual_router_id 2
              priority 101
              advert_int 1
              virtual_ipaddress {
                  {{ CLUSTER_APIENDPOINT_HOST }}
              }
          }
      - path: /etc/netplan/50-cloud-init.yaml
        owner: root:root
        permissions: '0644'
        content: |
          network:
              ethernets:
                  enp2s0:
                      dhcp4: true
              version: 2
      - path: /tmp/akeys
        owner: root:root
        permissions: '0644'
        content: {{ SSH_PUB_KEY_CONTENT }}
      - path : /etc/netplan/60-ironicendpoint.yaml
        owner: root:root
        permissions: '0644'
        content: |
          network:
            version: 2
            renderer: networkd
            bridges:
              ironicendpoint:
                interfaces: [enp1s0]
                dhcp4: yes
{% else %}
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: {{ CLUSTER_NAME }}-controlplane
spec:
  replicas: 1
  version: {{ KUBERNETES_VERSION }}
  infrastructureTemplate:
    kind: Metal3MachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
    name: {{ CLUSTER_NAME }}-controlplane
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: {{ " '{{ ds.meta_data.name }}' " }}
        kubeletExtraArgs:
          node-labels: 'metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}'
          provider-id: 'metal3://{{ '{{ ds.meta_data.uuid }}' }}'
    joinConfiguration:
      nodeRegistration:
        name: {{ " '{{ ds.meta_data.name }}' " }}
        kubeletExtraArgs:
          node-labels: 'metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}'
          provider-id: 'metal3://{{ '{{ ds.meta_data.uuid }}' }}'
    clusterConfiguration:
      apiServer:
        extraArgs:
    preKubeadmCommands:
      - mv /tmp/nmstate.yaml /home/ubuntu/nmstate.yaml
      - ip link set dev enp2s0 up
      - dhclient enp2s0
      - mv /tmp/akeys /home/ubuntu/.ssh/authorized_keys
      - chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
      - apt update -y
{% if CAPI_VERSION != 'v1alpha4' %}
        - netplan apply
{% endif %}
      - >-
        apt install net-tools gcc linux-headers-$(uname -r) bridge-utils
        apt-transport-https ca-certificates curl gnupg-agent
        software-properties-common -y
      - apt install -y keepalived && systemctl stop keepalived
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      - echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
      - apt update -y
      - apt install docker-ce docker-ce-cli containerd.io kubelet kubeadm kubectl -y
      - systemctl enable --now docker kubelet
      - if (curl -sk --max-time 10 https://{{ CLUSTER_APIENDPOINT_HOST }}:6443/healthz); then echo "keepalived already running";else systemctl start keepalived; fi
      - usermod -aG docker ubuntu
    postKubeadmCommands:
      - mkdir -p /home/ubuntu/.kube
      - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
      - systemctl enable --now keepalived
      - chown ubuntu:ubuntu /home/ubuntu/.kube/config
    files:
        - path: /etc/keepalived/keepalived.conf
          content: |
            ! Configuration File for keepalived
            global_defs {
                notification_email {
                sysadmin@example.com
                support@example.com
                }
                notification_email_from lb@example.com
                smtp_server localhost
                smtp_connect_timeout 30
            }
            vrrp_instance VI_2 {
                state MASTER
                interface enp2s0
                virtual_router_id 2
                priority 101
                advert_int 1
                virtual_ipaddress {
                    {{ CLUSTER_APIENDPOINT_HOST }}
                }
            }
        - path: /tmp/akeys
          owner: root:root
          permissions: '0644'
          content: {{ SSH_PUB_KEY_CONTENT }}
{% if CAPI_VERSION != 'v1alpha4' %}
        - path: /etc/netplan/50-cloud-init.yaml
          owner: root:root
          permissions: '0644'
          content: |
            network:
                ethernets:
                    enp2s0:
                        dhcp4: true
                version: 2
        - path : /etc/netplan/60-ironicendpoint.yaml
          owner: root:root
          permissions: '0644'
          content: |
            network:
              version: 2
              renderer: networkd
              ethernets:
                  enp1s0:
                      dhcp4: false
              bridges:
                ironicendpoint:
                  interfaces: [enp1s0]
                  dhcp4: yes
{% else %}
        - path : /tmp/nmstate.yaml
          owner: root:root
          permissions: '0644'
          content: |
            interfaces:
            - description: Provisioning
              ethernet:
                auto-negotiation: true
                duplex: full
                speed: 1000
              ipv4:
                address:
                - ip: {{ '{{ ds.meta_data.net1_ip }}' }}
                  prefix-length: 24
                enabled: true
                dhcp: false
              ipv6:
                address:
                - ip: {{ '{{ ds.meta_data.net1_ip6 }}' }}
                  prefix-length: 64
                enabled: true
              mtu: 1500
              name: eth0
              state: up
              type: ethernet
            - description: Baremetal
              ethernet:
                auto-negotiation: true
                duplex: full
                speed: 1000
              ipv4:
                address:
                - ip: {{ '{{ ds.meta_data.net2_ip }}' }}
                  prefix-length: 24
                enabled: true
                dhcp: false
              ipv6:
                address:
                - ip: {{ '{{ ds.meta_data.net2_ip6 }}' }}
                  prefix-length: 64
                enabled: true
              mtu: 1500
              name: eth1
              state: up
              type: ethernet
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.16.111.1
                next-hop-interface: eth1
              - destination: ::/0
                next-hop-address: 2001:0db8:85a3::1
                next-hop-interface: eth1
            dns-resolver:
              config:
                server:
                - 2001:4860:4860::8888
                - 8.8.8.8
{% endif %}
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
kind: Metal3MachineTemplate
metadata:
  name: {{ CLUSTER_NAME }}-controlplane
spec:
  template:
    spec:
      image:
        url: {{ IMAGE_URL }}
        checksum: {{ IMAGE_CHECKSUM }}
{% if CAPI_VERSION == 'v1alpha4' %}
      dataTemplate:
        name: {{ CLUSTER_NAME }}-cp-template
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
kind: Metal3DataTemplate
metadata:
  name: {{ CLUSTER_NAME }}-cp-template
spec:
  metaData:
    objectNames:
      - key: name
        object: machine
      - key: local-hostname
        object: machine
      - key: local_hostname
        object: machine
    ipAddresses:
      - key: net1_ip
        start: 172.22.0.20
        end: 172.22.0.30
      - key: net2_ip
        subnet: 192.168.111.20/24
      - key: net1_ip6
        start: fd2e:6f44:5dd8:b856::20
        end: fd2e:6f44:5dd8:b856::ff00
        step: 10
      - key: net2_ip6
        start: 2001:0db8:85a3::20
        end: 2001:0db8:85a3::ff00
        step: 10
  networkData:
    links:
      ethernets:
        - type: phy
          id: enp1s0
          macAddress:
            fromHostInterface: eth0
        - type: phy
          id: enp2s0
          macAddress:
            fromHostInterface: eth1
    networks:
      ipv4:
        - id: provisioning
          link: enp1s0
          ipAddress:
            start: 172.22.0.20
            end: 172.22.0.29
            subnet: 172.22.0.0/24
            step: 1
          netmask: 24
        - id: baremetal
          link: enp2s0
          ipAddress:
            start: 192.168.111.20
            end: 192.168.111.29
            subnet: 192.168.111.0/24
            step: 1
          netmask: 24
          routes:
            - network: 0.0.0.0
              netmask: 0
              gateway: 192.168.111.1
              services:
                dns:
                  - 8.8.8.8
    services:
      dns:
        - 8.8.4.4
{% endif %}
{% endif %}
