{% if CAPI_VERSION == 'v1alpha2' %}
apiVersion: cluster.x-k8s.io/v1alpha2
{% else %}
apiVersion: cluster.x-k8s.io/v1alpha3
{% endif %}
kind: MachineDeployment
metadata:
  name: {{ CLUSTER_NAME }}-md-0
  labels:
    cluster.x-k8s.io/cluster-name: {{ CLUSTER_NAME }}
    nodepool: nodepool-0
spec:
{% if CAPI_VERSION != 'v1alpha2' %}
  clusterName: {{ CLUSTER_NAME }}
{% endif %}
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ CLUSTER_NAME }}
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ CLUSTER_NAME }}
        nodepool: nodepool-0
    spec:
{% if CAPI_VERSION != 'v1alpha2' %}
      clusterName: {{ CLUSTER_NAME }}
{% endif %}
      version: {{ KUBERNETES_VERSION }}
      bootstrap:
        configRef:
          name: {{ CLUSTER_NAME }}-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/{{ CAPI_VERSION }}
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: {{ CLUSTER_NAME }}-md-0
        apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
{% if CAPI_VERSION == 'v1alpha2' %}
        kind: BareMetalMachineTemplate
{% else %}
        kind: Metal3MachineTemplate
{% endif %}
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
{% if CAPI_VERSION == 'v1alpha2' %}
kind: BareMetalMachineTemplate
{% else %}
kind: Metal3MachineTemplate
{% endif %}
metadata:
  name: {{ CLUSTER_NAME }}-md-0
spec:
  template:
    spec:
      image:
        url: {{ IMAGE_URL }}
        checksum: {{ IMAGE_CHECKSUM }}
{% if CAPI_VERSION == 'v1alpha4' %}
      dataTemplate:
        name: {{ CLUSTER_NAME }}-md-template
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPI_VERSION }}
kind: Metal3DataTemplate
metadata:
  name: {{ CLUSTER_NAME }}-md-template
spec:
  metaData:
    objectNames:
      - key: name
        object: machine
      - key: local-hostname
        object: machine
      - key: local_hostname
        object: machine
    ipAddresses:
      - key: net1_ip
        start: 172.22.0.20
        end: 172.22.0.30
      - key: net2_ip
        subnet: 192.168.111.20/24
      - key: net1_ip6
        start: fd2e:6f44:5dd8:b856::20
        end: fd2e:6f44:5dd8:b856::ff00
        step: 10
      - key: net2_ip6
        start: 2001:0db8:85a3::20
        end: 2001:0db8:85a3::ff00
        step: 10
  networkData:
    links:
      ethernets:
        - type: phy
          id: enp1s0
          macAddress:
            fromHostInterface: eth0
        - type: phy
          id: enp2s0
          macAddress:
            fromHostInterface: eth1
    networks:
      ipv4:
        - id: provisioning
          link: enp1s0
          ipAddress:
            start: 172.22.0.30
            end: 172.22.0.39
            subnet: 172.22.0.0/24
            step: 1
          netmask: 24
        - id: baremetal
          link: enp2s0
          ipAddress:
            start: 192.168.111.30
            end: 192.168.111.39
            subnet: 192.168.111.0/24
            step: 1
          netmask: 24
          routes:
            - network: 0.0.0.0
              netmask: 0
              gateway: 192.168.111.1
              services:
                dns:
                  - 8.8.8.8
    services:
      dns:
        - 8.8.4.4
{% endif %}
---
{% if CAPI_VERSION == 'v1alpha2' %}
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
{% else %}
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
{% endif %}
kind: KubeadmConfigTemplate
metadata:
  name: {{ CLUSTER_NAME }}-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: {{ " '{{ ds.meta_data.name }}' " }}
          kubeletExtraArgs:
            node-labels: 'metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}'
            provider-id: 'metal3://{{ '{{ ds.meta_data.uuid }}' }}'
      preKubeadmCommands:
        - mv /tmp/nmstate.yaml /home/ubuntu/nmstate.yaml
        - ip link set dev enp2s0 up
        - dhclient enp2s0
        - mv /tmp/akeys /home/ubuntu/.ssh/authorized_keys
        - chown ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
        - apt update -y
{% if CAPI_VERSION != 'v1alpha4' %}
        - netplan apply
{% endif %}
        - >-
          apt install apt-transport-https ca-certificates
          curl gnupg-agent software-properties-common -y
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
        - echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
        - apt update -y
        - apt install docker-ce docker-ce-cli containerd.io kubelet kubeadm kubectl -y
        - systemctl enable --now docker kubelet
        - usermod -aG docker ubuntu
      files:
        - path: /tmp/akeys
          owner: root:root
          permissions: '0644'
          content: {{ SSH_PUB_KEY_CONTENT }}
{% if CAPI_VERSION != 'v1alpha4' %}
        - path: /etc/netplan/50-cloud-init.yaml
          owner: root:root
          permissions: '0644'
          content: |
            network:
                ethernets:
                    enp1s0:
                        dhcp4: true
                    enp2s0:
                        dhcp4: true
                version: 2
{% else %}
        - path : /tmp/nmstate.yaml
          owner: root:root
          permissions: '0644'
          content: |
            interfaces:
            - description: Provisioning
              ethernet:
                auto-negotiation: true
                duplex: full
                speed: 1000
              ipv4:
                address:
                - ip: {{ '{{ ds.meta_data.net1_ip }}' }}
                  prefix-length: 24
                enabled: true
                dhcp: false
              ipv6:
                address:
                - ip: {{ '{{ ds.meta_data.net1_ip6 }}' }}
                  prefix-length: 64
                enabled: true
              mtu: 1500
              name: eth0
              state: up
              type: ethernet
            - description: Baremetal
              ethernet:
                auto-negotiation: true
                duplex: full
                speed: 1000
              ipv4:
                address:
                - ip: {{ '{{ ds.meta_data.net2_ip }}' }}
                  prefix-length: 24
                enabled: true
                dhcp: false
              ipv6:
                address:
                - ip: {{ '{{ ds.meta_data.net2_ip6 }}' }}
                  prefix-length: 64
                enabled: true
              mtu: 1500
              name: eth1
              state: up
              type: ethernet
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.16.111.1
                next-hop-interface: eth1
              - destination: ::/0
                next-hop-address: 2001:0db8:85a3::1
                next-hop-interface: eth1
            dns-resolver:
              config:
                server:
                - 2001:4860:4860::8888
                - 8.8.8.8
{% endif %}
