- name: Install packages on Ubuntu
  block:
    - name: Install packages using standard package manager
      package:
        name: "{{ package.ubuntu.package +  package.ubuntu.libvirt }}"
        state: present
      become: true
    - name: Install packages using pip
      pip:
        name: "{{ package.ubuntu.pip }}"
        state: present
      become: true
  when: ansible_facts['distribution'] == "Ubuntu"


- name: Install packages on CentOS
  block:
    - name: Install packages using standard package manager
      block: 
        - name: Install packages on rhel7
          when: ansible_lsb.major_release|int == 7
          package:
             name: "{{ package.centos.package +  package.centos.libvirt.rhel7 }}"
             state: present
        - name: Install packages on rhel8
          when: ansible_lsb.major_release|int == 8
          package:
             name: "{{ package.centos.package + package.centos.libvirt.rhel8 }}"
             state: present
      become: true
    - name: Install packages using pip
      pip:
        name: "{{ package.centos.pip }}"
        state: present
      become: true
  when: ansible_os_family == "RedHat"
